### ISSUE TITLE
Register config + behavior keymap

### ISSUE THREAD

**Issue by mattiasbonte** [rareitems/printer.nvim#9]
Hi!

I noticed 2 things which would be nice to have in the config.

- A config to chose the register where to store the yank inside.
- And would it also be possible to, for example, have a keybind where it's automatically the `yank` behavior and one where it is the `insert_below` behavior?

Cheers!

**Comment by rareitems** [comment]
Added it in https://github.com/rareitems/printer.nvim/commit/37739d2956011436daa2e016d1514de3247c3b46
